#%RAML 0.8
title: SpeakEasy
baseUri: http://speakz.ca
version: 0.3
/:
  get:
    description: Returns a list of most recent 100 posts of your followers
    responses:
      200: 
        body:
          application/json:
            example: | 
             {
                messages: 
                [{
                    "uri" : "/Users/wightman/Speakz/345
                    "displayname" : "wightstuff"
                    "timePosted": "2010-12-16T12:14:05+00:00",
                    "messageContents": "This is an example message"
                    "messageID" : 345            
                },
                {
                    "uri" : "/Users/bogart/Speakz/344
                    "displayname" : "Boogers"
                    "timePosted": "2010-12-16T12:14:03+00:00",
                    "messageContents": "This is an older example message"               
                    "messageID" : 344
                }],
             }
  
/Login: 
  post:
    description: Logs in a user, establishes a session
    responses:
      201: #login successful
      401: #not authorized

  delete:
    description: Logs out a user, destroys the session
    responses:
      200: #success

/Users:
  get:
    description: Return a list of users
    responses:
      200:

/Users/{username}: 
  get:
    description: Returns the information for the user, including number followers, following, mentions
    responses:
      200:
        body:
          application/json:
            example: |
             {
                "username" : "user",
                "displayName" : "Test User",
                "tagline" : "Java is my life.",
                "followers" : 2,
                "following" : 2,
                "mentions" : 3
             }
      401: #not authorized

  post:
    description: Submits a new message to the logged in feed
    body:
      application/json:
        example: |
          { 
            "messageContents" : "Example message to post."
          }
    responses:
      201: #Successfully added
        body:
          application/json:
            example: |
              {
                    "message": {
                        "uri" : "/Users/wightstuff/Speakz/345",
                        "displayname" : "wightstuff",
                        "timePosted": "2010-12-16T12:14:05+00:00",
                        "messageContents": "This is a posted message",
                        "messageID" : 345            
                    }
              }
      401: #not authorized

/Users/{username}/Speakz:
  get:
    description: Returns a list of all Speakz from the user.
    responses: 
      200:

/Users/{username}/Speakz/{speakzid}:
  delete: 
    description: Undisplays a specified message if in the logged in feed
  put:
    description: Edit your own Speak

/Users/{username}/Following:
     get:
      description: Returns a list of users this person follows
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  [{
                      "userName": "JohnDoe",
                      "schoolID": "3509321"               
                  },
                  {
                      "userName": "JaneDoe",
                      "schoolID": "3509322"               
                  }],
                  "following": 2
                }
        401: #not authorized

     post:
      description: Follow a new person
      responses:
        201: #Successfully added
          body:
            application/json:
              example: |
                {"user": {
                     "userName": "JaneDoe",
                     "schoolID": "3509322" 
                }
        401: #not authorized


/Users/{username}/Followers:
     get:
      description: Returns the list of users following this person
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  users:
                  [{
                      "userName": "JohnDoe",
                      "schoolID": "3509321"               
                  },
                  {
                      "userName": "JaneDoe",
                      "schoolID": "3509322"               
                  }],
                  "followers": 2
                }
        401: #not authorized

/Users/{username}/Mentions:
  get:
    description: Returns list of mentions of a person.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "messages": 
                   [{
                     "uri" : "/Users/wightstuff/Speakz/345",
                     "displayname" : "wightstuff",
                     "timePosted": "2010-12-16T12:14:05+00:00",
                     "messageContents": "This is a @user",
                     "messageID" : 345
                   },
                   {
                     "uri" : "/Users/Boogers/Speakz/345",
                     "displayname" : "Boogers",
                     "timePosted": "2010-10-16T12:04:05+00:00",
                     "messageContents": "This is a @user",
                     "messageID" : 222            
                   }],
                "mentions": 2
              }
      401: #not authorized

/Users/{username}/Preferences:
  get:
    description: Returns profile settings
    responses:
      200:

  post: 
    description: Add new profile settings
    responses:
      200:

#/User/{username}/Recent: Not used

/Hashtag/{hashtag}:
  get:
    description: Displays last 100 tweets with given hashtag.
    responses:
      200: